### ISSUE TITLE
Error on build of default template project

### ISSUE THREAD

**Issue by Russtopia** [leafi/love-eclipse-ldt#4]
Hi, I tried installing and get this error when trying to build the default project:

Exception in thread "main" com.naef.jnlua.LuaRuntimeException: C:\Users\russtopia\workspace\hello-love\main.lua:10: attempt to index global 'love' (a nil value)
    at com.naef.jnlua.LuaState.lua_pcall(Native Method)
    at com.naef.jnlua.LuaState.call(LuaState.java:555)
    at org.eclipse.ldt.support.lua51.internal.interpreter.JNLua51Launcher.run(JNLua51Launcher.java:128)
    at org.eclipse.ldt.support.lua51.internal.interpreter.JNLua51Launcher.main(JNLua51Launcher.java:143)

Platform: Win7-64, JRE 1.8.0_71, Eclipse Mars, love-eclipse-ldt 0.10.1

**Comment by sirskunkalot** [comment]
Hi Russtopia,

this looks like it is not a problem with love-eclipse-ldt but your chosen runtime. Only installing love-eclipse-ldt on a fresh install of eclipse LDT does not enable you to run löve code. You still need to install the löve runtime on your PC and enable it in eclipse LDT. This project only provides the Execution Environment for the löve runtime (see the LDT wiki pages: https://wiki.eclipse.org/LDT/User_Area/User_Guides/User_Guide_1.3#Execution_Environment for more information about an EE). If you need help setting up löve, the wiki at https://wiki.eclipse.org/LDT is a good start.

**Comment by Russtopia** [comment]
OK, I'll go over my setup again, I probably just missed something :) Thanks!
